# (clock)
set_property PACKAGE_PIN W5 [get_ports {clk_100}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk_100}]

# (switches)enable_master, display_result_switch, ops 
set_property PACKAGE_PIN R2 [get_ports {enable_master}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable_master}]
set_property PACKAGE_PIN T1 [get_ports {welcome_screen_switch}]
set_property IOSTANDARD LVCMOS33 [get_ports {welcome_screen_switch}]
set_property PACKAGE_PIN T2 [get_ports {display_result_switch}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_result_switch}]
set_property PACKAGE_PIN W15 [get_ports {ops[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ops[4]}]
set_property PACKAGE_PIN W17 [get_ports {ops[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ops[3]}]
set_property PACKAGE_PIN W16 [get_ports {ops[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ops[2]}]
set_property PACKAGE_PIN V16 [get_ports {ops[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ops[1]}]
set_property PACKAGE_PIN V17 [get_ports {ops[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ops[0]}]

# (leds) show_enable_master, show_display_result_switch, show_op0_add, show_op1_sub, show_op2_mult, show_op3_div
set_property PACKAGE_PIN L1 [get_ports {show_enable_master}]
set_property IOSTANDARD LVCMOS33 [get_ports {show_enable_master}]
set_property PACKAGE_PIN P1 [get_ports {show_welcome_screen_switch}]
set_property IOSTANDARD LVCMOS33 [get_ports {show_welcome_screen_switch}]
set_property PACKAGE_PIN W3 [get_ports {show_display_result_switch}]
set_property IOSTANDARD LVCMOS33 [get_ports {show_display_result_switch}]
set_property PACKAGE_PIN W18 [get_ports {show_op4_power}]
set_property IOSTANDARD LVCMOS33 [get_ports {show_op4_power}]
set_property PACKAGE_PIN V19 [get_ports {show_op3_div}]
set_property IOSTANDARD LVCMOS33 [get_ports {show_op3_div}]
set_property PACKAGE_PIN U19 [get_ports {show_op2_mult}]
set_property IOSTANDARD LVCMOS33 [get_ports {show_op2_mult}]
set_property PACKAGE_PIN E19 [get_ports {show_op1_sub}]
set_property IOSTANDARD LVCMOS33 [get_ports {show_op1_sub}]
set_property PACKAGE_PIN U16 [get_ports {show_op0_add}]
set_property IOSTANDARD LVCMOS33 [get_ports {show_op0_add}]

# (push_buttons) each number display, reset
set_property PACKAGE_PIN U18 [get_ports {reset}]
set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
set_property PACKAGE_PIN T18 [get_ports {buttons[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[0]}]
set_property PACKAGE_PIN U17 [get_ports {buttons[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[1]}]
set_property PACKAGE_PIN T17 [get_ports {buttons[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[2]}]
set_property PACKAGE_PIN W19 [get_ports {buttons[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[3]}]

# (7-segment diplay) enable_anodes, 8bits for the 7-segment
set_property PACKAGE_PIN W4 [get_ports {enable_anodes[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable_anodes[3]}]
set_property PACKAGE_PIN V4 [get_ports {enable_anodes[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable_anodes[2]}]
set_property PACKAGE_PIN U4 [get_ports {enable_anodes[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable_anodes[1]}]
set_property PACKAGE_PIN U2 [get_ports {enable_anodes[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {enable_anodes[0]}]

set_property PACKAGE_PIN W7 [get_ports {result[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[7]}]
set_property PACKAGE_PIN W6 [get_ports {result[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[6]}]
set_property PACKAGE_PIN U8 [get_ports {result[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[5]}]
set_property PACKAGE_PIN V8 [get_ports {result[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[4]}]
set_property PACKAGE_PIN U5 [get_ports {result[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[3]}]
set_property PACKAGE_PIN V5 [get_ports {result[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[2]}]
set_property PACKAGE_PIN U7 [get_ports {result[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[1]}]
set_property PACKAGE_PIN V7 [get_ports {result[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[0]}]